### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by martoio** [corbindeveloper/prj-rev-bwfs-dasmoto#1]
Good job on separating the HTML into sections! One thing you might want to consider is changing the ``<div>`` into a ``<section>`` to improve the semantics of your code.
If you aren't familiar with semantic HTML: http://www.hongkiat.com/blog/html-5-semantics/
Example:
```
<!-- First section -->
<section> <!-- or <div>, but <section> is more semantic -->
 <h2 class="brushes">Brushes</h2>
 <img src="#" alt="#" />
 <h3>Text</h3>
 <p>
  Lorem <span class="price">ipsum</span>
 </p>
</section>
```
https://github.com/corbindeveloper/prj-rev-bwfs-dasmoto/blob/b06b7926968e93a8f4ddff87ed55e218e5dd000c/DasmotosArts/home.html#L12-L17

**Comment by corbindeveloper** [comment]
Thank you for the article reference! I'm definitely in a bad habit of over-using div's instead of utilizing section, aside, ect.
