### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [corbindeveloper/prj-rev-bwfs-dasmoto#2]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/corbindeveloper/prj-rev-bwfs-dasmoto/blob/b06b7926968e93a8f4ddff87ed55e218e5dd000c/DasmotosArts/home.html#L14

**Comment by corbindeveloper** [comment]
Thank you.
