### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [corbindeveloper/prj-rev-bwfs-dasmoto#3]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/
The ampersand should be written as:
``&amp;``

https://github.com/corbindeveloper/prj-rev-bwfs-dasmoto/blob/b06b7926968e93a8f4ddff87ed55e218e5dd000c/DasmotosArts/home.html#L11

**Comment by corbindeveloper** [comment]
Thanks, figured I should have after doing the Excursion and using the copyright entity.
