### ISSUE TITLE
Duplicate CSS

### ISSUE THREAD

**Issue by martoio** [corbindeveloper/prj-rev-bwfs-dasmoto#4]
See how this code repeats 3 times for each ``h2``?

https://github.com/corbindeveloper/prj-rev-bwfs-dasmoto/blob/b06b7926968e93a8f4ddff87ed55e218e5dd000c/DasmotosArts/main.css#L14-L16

What happens if the client decides to change the font-size and the color for the ``h2``s? All of a sudden you have to make 6 edits in your code, when in reality you are only changing 2 things. A better approach would be:
```
h2{
 font-size:32px;
 font-weight:bold;
 color: white;
}
#brushes {
 background-color: mediumspringgreen;
}

#frames {
 background-color: lightcoral;
}

#paint {
 background-color: skyblue;
}
```

**Comment by corbindeveloper** [comment]
Ah ha! I couldn't quite get it right in my head while maintaining the individual backgrounds. Thank you!
